name = "${WORKER_NAME}"
main = "src/index.ts"
compatibility_date = "2024-02-17"

[vars]
API_KEY = "${API_KEY}"
OPENAI_API_KEY = "${OPENAI_API_KEY}"

[[d1_databases]]
binding = "${D1_DATABASE_BINDING}"
database_name = "${D1_DATABASE_NAME}"
database_id = "${D1_DATABASE_ID}"