name = "edge-scribe"
main = "src/index.ts"
compatibility_date = "2024-02-17"

[vars]
API_KEY = ""
OPENAI_API_KEY = ""

[[d1_databases]]
binding = "DB"
database_name = ""
database_id = ""

[triggers]
crons = ["0 0 * * *"]